conf_open_source_api_latest.py

Changes (in compare with original file):
- added parameter `--api=latest`
- changed the year

Add api_latest conf

---

README.txt
conf_linux_public.py
conf_linux_public_api_latest.py

+ updates for Install package layout

[Build configs][do not merge] Config files renamed

---

conf_how_to.py
conf_linux_public.py
conf_linux_public_api_latest.py

'DEFAULT_OPTIONS' renamed to 'options'
'Stage' renamed to 'stage'

[Build configs] API updates

---

conf_linux_public.py
conf_linux_public_api_latest.py

Implemented:
NB: Need to merge with this Pull request: ...

Add clean cmake build and some improvements

---

conf_linux_public.py

Created to support: https://github.com/Intel-Media-SDK/MediaSDK/pull/296
This PR depends on: https://github.com/Intel-Media-SDK/MediaSDK/pull/303

Change cmake parameters

---

conf_linux_public.py

Fixes: https://github.com/Intel-Media-SDK/infrastructure/issues/95

Replace `DENABLE_TOOLS`, fixes #95

---

conf_how_to.py
conf_linux_public.py

[Product configs] Hot fix

---

infrastructure_version.py

- Added deploying infrastructure

Switch to last infrastructure revision

---

infrastructure_version.py

Migration to new infra with aiding LD_LIBRARY_PATH for tests with path to dispatcher, an issue was fixed.

Adding LD_LIBRARY_PATH for tests - part 2

---

conf_linux_public.py
infrastructure_version.py

Add branch 'master' to switch in libva repo in order to prevent looking for release branch in this repo

Config for release branches

---

conf_linux_public.py

Change location to /usr/local/

Fixed wrong install location for LibVa deb package

---

conf_libva.py

Created draft for LibVA configuration

Separated configuration for LibVA

---

infrastructure_version.py

Updated deploying infrastructure for pull request

---

conf_linux_public.py

Get LibVA version that is defined

Define LibVA version

---

conf_linux_public.py

Fix libva version

---

conf_linux_public.py

Separated libva build 18.3 release

---

conf_linux_public.py

Separated LibVA build
Libva was built to /dependencies on machine

Separated libva build

---

conf_media_driver.py
infrastructure_version.py

Created separate config for media_driver build

Added build config for media driver

---

conf_gmmlib.py

Added config for gmmlib build through build scripts

Created configuration for gmmlib build

---

infrastructure_version.py

build_number returns number from "master" branch
fix for extract_archive function

[Infra] Updates

---

infrastructure_version.py

[Infra] git_worker updates

---

infrastructure_version.py

- Added check author name and email as pre commit check
- Used branch like refs/pull/id/merge in pull request pollers

Update infrastructure version

---

conf_libva.py
conf_linux_public.py
manifest.yml

+ manifest was created;
+ 'tags/...' does not need;

[Infra] libva_conf updates

---

conf_libva.py

Added config for libva-utils build to libva config

Added libva-utils build

---

infrastructure_version.py

Updates:
- Added prototype of buildbot configuration for driver (#209)
- Added libva-utils repo (#212)
- Disable fastboot build for mss2018_r2 branch (#211)
- Removed commit-time argument for build script cmd (#208)

Enabled CI for media driver

---

infrastructure_version.py

Build scripts can work with manifest information

[Infrastructure] Add dependencies support

---

conf_libva.py

Add cmd to build with required options for msdk

Change config according requirements

---

conf_gmmlib.py

Update config with required build option

---

conf_igc.py

Created product config for igc to build it and pack to rpm/deb packages

Created prototype config for intel-graphics-compiler build

---

infrastructure_version.py

[Infra] Add test_runner.py for Driver

---

manifest.yml

Added gmmlib, igc, opencl_runtime to manifest

Added components to manifest

---

conf_linux_public.py

Extended build log to provide all command lines with arguments for building and linking libraries.

Enabled full build log

---

conf_opencl.py
infrastructure_version.py

Configuration for OpenCL-runtime NEO to build, pack via build scripts.

Added configuration for OpenCL-runtime build

---

conf_linux_public.py
driver/conf_media_driver.py
infrastructure_version.py

Added files to resolve dependencies while installing rpm/deb packages

Added config files to msdk packages

---

driver/conf_media_driver.py
infrastructure_version.py

Update infrastructure for 19.1

---

driver/conf_media_driver.py
infrastructure_version.py

Release-internal build also enabled

[Buildbot][Driver] Enable Debug build

---

conf_linux_public.py
infrastructure_version.py

Revert "Update infrastructure version"

---

infrastructure_version.py

- Fixed problem with duplication of test sessions.
- Trigger activates one time forl last build even if some builds check dependencies in time.

[Buildbot] Enable fix for build scheduling

---

conf_windows_public.py

- https://github.com/Intel-Media-SDK/MediaSDK/pull/1423

[Windows] Update dev package layout

---

manifest.yml

[One CI][IGC] Change version

---

manifest.yml

[Copyright check] Fixed skipping files by paths

---

conf_linux_public.py

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

[CI][MediaSDK] Add -Werror flag for clang

---

conf_linux_public.py
conf_media_driver.py
manifest.yml

(cherry picked from commit 9f9f93c1971aca3d1e2249aa6cbde3762f9819c1)

Switch from clang 10 to 11 version for CI (#360)
